### ISSUE TITLE
Find out which institution ULS is

### ISSUE THREAD

**Issue by StefKirsch** [StefKirsch/clean-and-enrich-phd-supervisor-data#10]
In the NARCIS dataset there are abbreviations for the institutions that can't be found directly in OA. So we need to unabbreviate them first, but it's unclear what the abbreviation ULS stands for.

**Comment by tamarinde** [comment]
https://colab.research.google.com/drive/1A_YcE8aELiCwBQJ7s30EFsTcwhZ2BByP?usp=sharing

**Comment by StefKirsch** [comment]
ULS was still not listed there, but I noticed it affected only one publication that I could just look up :)
